name: Terraform Deploy GKE

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: plataformas2-356563
      REGION: us-central1
      CLUSTER_NAME: mygpccluster
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}  

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        working-directory: ./google
        run: terraform init

      - name: Terraform Apply
        working-directory: ./google
        run: terraform apply -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }} 

      - name: Authenticate gcloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Get GKE Credentials
        run: |
          gcloud container clusters get-credentials $CLUSTER_NAME \
            --region $REGION \
            --project $PROJECT_ID

      - name: Output Static IP
        id: static_ip
        working-directory: ./google
        run: |
          STATIC_IP=$(terraform output -raw ingress_static_ip_address | tr -d '\n' | tr -d '\r')
          echo "STATIC_IP=$STATIC_IP" >> $GITHUB_ENV
          echo "Static IP: $STATIC_IP"

      - name: Trigger Helm workflow in Ecommerce-deploy
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          repository: Project-Plataformas2/Ecommerce-deploy
          event-type: terraform-finished
          client-payload: |
            {
              "STATIC_IP": "${{ env.STATIC_IP }}"
            }
